export const getProducts = () => {
  return [
    {regex: '(ABACAXI SCHRAMM CALD)', text: 'Abacaxi em calda'},
    {regex: '(ACEM KG|CARNE ACEM MOIDO)', text: 'Acém'},
    {regex: '(ACHOC PO TODDY 400G|ACHOC PO ITALAC SCH 400G|ACHOC PO TODDY 400G|ACHOC TODDY 400G|TODDY TRAD.400g)', text: 'Achocolatado'},
    {regex: '(ACUC.PURINHA 5KG|ACUCAR CRISTAL CARAVELAS 5KG|ACUCAR BIG BOM 5KG C)', text: 'Açúcar Cristal 5kg'},
    {regex: '(ACUCAR CRISTAL CARAVELAS 1KG|ACUCAR BIG BOM EXTRA|ACUCAR REF CARAVELAS 1KG|ACUCAR REF.CARAVELAS|ACUCAR A ALEGRE 1KG|ACUCAR CARAVELAS 1KG)', text: 'Açúcar Refinado 1kg'},
    {regex: '(ACUCAR MASCAVO LOWCU)', text: 'Açúcar Mascavo 300g'},
    {regex: '(ACUCAR UNIAO DEMERAR)', text: 'Açúcar Demerara 1kg'},
    {regex: '(ADOC LIQ ZERO CAL 100ML|ADOC.ZERO-CAL 100ML|ADOCANTE ZERO CAL LI|ADOC ZERO CAL SACARI)', text: 'Adoçante'},
    {regex: '(AGUA SANIT SUPREMA 1L|AGUA SANIT SUPREMA 2L|AGUA SANITARIA VAREK|AGUA SANITARIA TRIEX)', text: 'Água Sanitária'},
    {regex: '(ALHO GRANEL)', text: 'Alho'},
    {regex: '(AMEIXA OLE LT 150G C)', text: 'Ameixa em calda'},
    {regex: '(AMAC URCA FLORAL 2L|AMAC FLEUR D YPE ACONCHEGO AZUL 2L|AMAC FLOR YPE LV 2L|AMAC.PLUSH 2L|AMAC.YPE AZUL PROMO|AMACIANTE YPE 2L)', text: 'Amaciante'},
    {regex: '(CARGA GILLETE MACH3 REG 3UN|DES STICK GILLETTE C|AP BARB BIC COMFORT TWIN NORMAL 2UN|AP BARB PRESTOBARBA U GRIP 3 2UN|AP SUPER SHAVE 2UN|AP SUPER SHAVE 3 BAR)', text: 'Aparelho de Barbear'},
    {regex: '(FC APRESUNTADO PEPER|APRESUNTADO FAT SADIA KG|APRESUNTADO PEPERI F|APRESUN PEPERI FAT)', text: 'Apresuntado'},
    {regex: '(ARROZ PARBOILIZADO CAMIL 5KG|ARROZ PAN FERRO 5K P|ARROZ PARB.B.LEGAL|ARROZ PARB.RAROZ|ARROZ PARBOILIZADO CAMIL 5KG|ARROZ PARBOLIZADO BLUE VILLE 5KG|SOBRADINHO 5K PARBOI|ALBARUSKA 5KG PARBOI|ALBARUSKA 5KG T 1|ARROZ PANELA FERRO 5|ARROZ PILECCO 5KG PA)', text: 'Arroz 5kg'},
    {regex: '(ATUM COQUEIRO NAT 17|ATUM BALTICO LT 170G|ATUM ROBINSON CRUSOE)', text: 'Atum'},
    {regex: '(AVEIA FLOCOS N.LIFE|AVEIA SANJER 250G FL|AVEIA YOKI FLOCOS 500G|AVEIA YOKI FLOCOS FINOS 500G)', text: 'Aveia'},
    {regex: '(AZEITE PURO GALLO VD 500ML|AZ.OLIV.CONDE 500ML|AZEITE COCINERO 500M|AZEITE EX VIRGEM FAMIGLIA DORO VD 500ML|AZEITE EX VIRGEM LA ESPANOLA VD 500ML|AZEITE BALTICO CLASS)', text: 'Azeite'},
    {regex: '(AZEITONA DIZA SACHE|AZEITONA VDE FAT CAMPO BELO SCH 150G|AZEIT.FAT.DIZA 100g|AZEITONA DIZA 100)', text: 'Azeitona'},
    {regex: '(BACALHAU LING 8 10)', text: 'Bacalhau'},
    {regex: '(BACON MANTA SADIA KG|BACON MANTA SADIA KG|BACON SANTA ROSA PED|BACON SADIA)', text: 'Bacon'},
    {regex: '(BECEL 250G|BECEL 500G|BECEL 500G MANTEIGA|CR VEGETAL PRIME 500|CR.VEG.BECEL 500G|CREME VEGETAL CSAL TRAD BECEL 500G|MARG CLAYBOM 500G|CR VEGETAL BECEL 500)', text: 'Margarina'},
    {regex: '(BISC AGUA E SAL SPECIALAT 400G|BISC AGUA E SAL TRIUNFO 375G|BISC.A.SAL ZABET 400|BISC TRIUNFO SALG 37)', text: 'Bolacha Água e Sal'},
    {regex: '(BISC.RENATA LAM.360G|BISCOITO ZABET 400G|BISCOITO ZABET MANTE|BISCOITO ZABET DOCE)', text: 'Bolacha Maizena'},
    {regex: '(BOMBOM NESTLE ESPECIALIDADES 300G|BOMBOM LACTA 289.2G|BOMBOM NESTLE 300G E|BOMBOM NESTLE ESPECIALIDADES 300G|BOMBOM GAROTO 250G S|BOMBOM GAROTO 300G S|BOMBOM LACTA 250 6G|BOMBOM NESTLE 251G E)', text: 'Caixa de Bombons'},
    {regex: '(C SECA PAINEIRA 500G)', text: 'Carne Seca'},
    {regex: '(CAFE COPPO 500G|CAFE 3 CORACOES VACU|CAFE 3 CORACOES 500G|CAFE ALMOF TRAD 3 CORACOES 500G|CAFE 3 COR.500g|CAFE 3 COR.PROMO|CAFE 3 CORACOES TRAD|CAFE ALMOF EXTRA FORTE BRASILEIRO 500G|CAFE BIGBOM 500G|CAFE VACUO EX FORTE MANHA 500G)', text: 'Café 500g'},
    {regex: '(CAFE SOLUVEL EXTRA FORTE 3 CORACOES 50G|CAFE 3 COR.SACHET|CAFE 3 CORACOES SOLU|CAFE SOL.PACAEMBU|CAFE SOLUVEL PELE SCH 50G|MELITTA SOLUVEL 50G|CAFE PACAEMBU SOLUVE)', text: 'Café Solúvel'},
    {regex: '(CALDO MAGGI 114G|CALDO MAGGI CARNE 114G|CALDO KNORR 114GR|CALDO KNORR GALINHA|CALDO KNORR LV12PG10|CALDO MAGGI 152G)', text: 'Caldo Knorr'},
    {regex: '(CANJICA HIKARI 500G|CANJICA KININO 500G|CANJICA SANJER BRANC|CANJICA MILHO YOKI 5)', text: 'Canjica'},
    {regex: '(CEBOLA MEDIA)', text: 'Cebola'},
    {regex: '(CENOURA MEDIA)', text: 'Cenoura'},
    {regex: '(CONTRA FILE KG|CARNE BOVINA CONTRA FILET EM BIFES)', text: 'Contra-Filé'},
    {regex: '(CHOC GAROTO BARRA 90|CHOC.HERSHEY S 110g|CHOC.HERSHEY S 92G)', text: 'Chocolate em Barra'},
    {regex: '(COCO RALADO SOCOCO 1|COCO RALADO MENINA 5|COCO FLOCOS MENINA10|COCO PREFERIDA 100g|COCO RALADO MENINA 1)', text: 'Coco Ralado'},
    {regex: '(CR DENTAL COLGATE TO|CR DENTAL COLGATE NA|CR DENT COLGATE NATU|CJ CR DENT COLGATE T|COLGATE MAXIMA PROTE|CR DENT COLGATE TOTA|CR DENT COLGATE TOTAL12 MINT 90G|CR.COLG.PROF.140G|CR.COLG.TOTAL WHITEN|KIT COLGATE TOTAL 2)', text: 'Pasta de Dentes'},
    {regex: '(CR LEITE PIRACANJUBA|CR LEIT/E SHEFA TP 20|CR DE LEITE ITALAC TP 200G|CR LEITE SHEFA TP 20|CR.LEITE JUSSARA TP|CR.LEITE SHEFA 200g|CREME LEITE JUSSARA)', text: 'Creme de Leite'},
    {regex: '(CR PENTEAR PANTENE 2)', text: 'Creme de Pentear'},
    {regex: '(CURIMBA INT. kg|CURIMBA KG)', text: 'Curimba'},
    {regex: '(CX MOLE KG)', text: 'Coxão Mole'},
    {regex: '(CHOPP A OUTRA LT 269|CERV PETRA LT 350ML|CERV.BHAM.MALZ.355ML|CERV.ITAI.MALZ.350M)', text: 'Cerveja (Malzbier)'},
    {regex: '(DES AERO REXONA WOMA|DES CR REXONA AP 48G|DESOD AERO MONANGE HID INTENSIVA 90G|DES AERO SUAVE WOMAN)', text: 'Desodorante Feminino'},
    {regex: '(DES SPRAY ZOG 90ML|DESOD AERO SUAVE SPORTFRESH 87G)', text: 'Desodorante Masculino'},
    {regex: '(DESINF TRIEX 2L|DESINFETANTE URCA EU|DESINF BUFALO FLORAL 2L|DESINF DETAX 2L|DESINF SANOL 2L LAV|DESINF SANOL LAVANDA 2L|DESINF URCA LAVANDA 2L|DESINF.SANOL FLOR.2L|DESINFETANTE BAK YPE|PINHO CANDURA VIOLET)', text: 'Desinfetante 2L'},
    {regex: '(DETERG LIQ SUPREMA FR VERMELHAS 500ML|DET.LIQ.MINUANO LIM.|DET.LIQ.MINUANO MACA|DET.LIQ.MINUANO MAR.|DET.LIQ.YPE PACK|DETERG LIQ SUPREMA FR VERMELHAS 500ML|DETERG LIQ SUPREMA LIMAO 500ML|DETERG LIQ SUPREMA NEUTRO 500ML|L LOUCA TRIEX 500ML)', text: 'Detergente'},
    {regex: '(CEPACOL 250ML|ENXAG.DENTICS PROM.)', text: 'Enxaguante Bucal'},
    {regex: '(ERVILHA QUERO SACHE|ERV.FUGINI SACHET|ERVILHA FUGINI 200G|ERVILHA FUGINI SCH 200G|ERVILHA QUERO MENOS SODIO 200G)', text: 'Ervilha 200g'},
    {regex: '(ESC DENT COLGATE ESSENCIAL CLEAN MACIA|ESC DENT J J REACH ULTRA CLEAN GRANDE|ESC DENT J J TEK|ESC.REACH.U.CLEAN MD|ESC DENT J J TEK DU|ESC DENT SORRISO TRI)', text: 'Escova de Dentes'},
    {regex: '(ESP.M.U.ESFREBOM C4|ESPONJA BRILHUS M US|ESPONJA ESFRELUX C 4|ESPONJA 3M TININDO L|ESPONJA ACO Q LUSTRO|ESPONJA M U SELECT 4UN)', text: 'Esponja'},
    {regex: '(CERESER MACA 660ML S|ESPUMA CERESER 660ML|ESPUMANT CERESER 660)', text: 'Espumante'},
    {regex: '(EXT TOM ELEFANTE 340G|EXT.TOM.LAT.ELE.340g|EXTRATO ELEFANTE LT|EXTRATO ELEFANTE PET|EXTRATO ELEFANTE 340)', text: 'Extrato de Tomate'},
    {regex: '(FAR.MILHO DEUSA 500G|FARINHA MILHO AMARELA YOKI 500G|FARINHA S ANTONIO MI)', text: 'Farinha de Milho'},
    {regex: '(FAR.TRIGO T.OFELIA 1|FARINHA TRIGO RENATA|FARINHA CLARICE 1KG|FARINHA DE TRIGO LILI 1KG|FARINHA DE TRIGO SANTA CLARA 1KG|FARINHA TRIGO BIG BO)', text: 'Farinha de Trigo'},
    {regex: '(FAROFA MAND HIKARI 5|FAROFA MONJOLINHO|FAROFA PRONTA MAND YOKI 500G|FAROFA YOKI 500G)', text: 'Farofa'},
    {regex: '(FEIJAO CABRERA 2KG|FEIJAO CABRERA PRETO|FEIJAO CAIPIRA 2KG C|FEIJAO KIBELLO 1KG C|FEIJAO SOBRADINHO 1K|FEIJAO DU DE 1KG PRE|FEIJAO CAIPIRA 1KG C|FEIJAO CARIOCA DA CASA TP 1 1KG|FEIJAO CREMOSO 1KG C|FEIJAO CREMOSO 2KG C|FEIJAO G.CAMPO 1KG)', text: 'Feijão'},
    {regex: '(FERM FLEISCHMANN 4UN|FERMENTO BIOL D BENTA SECO INST 10G)', text: 'Fermento Biológico'},
    {regex: '(FERM.PO D.BENTA 100g|FERMENTO PO OETKER 100G)', text: 'Fermento em Pó'},
    {regex: '(FOLHA ALUM WYDA 30CMX7.5M|FL.AL.WYDA 30CM|FOLHA ALUMINIO WYDA)', text: 'Folha de Papel Alumínio'},
    {regex: '(FUBA HIKARI 500G MIM|FUBA KODILAR 500G|FUBA YOKI 1KG|FUBA YOKI 500G)', text: 'Fubá'},
    {regex: '(GEL.OETKER LIMAO|GELAT.OETKER MORANGO|GELAT.OETKER UVA|PO GELATINA D OETKER|PO GELATINA OETKER 2)', text: 'Gelatina'},
    {regex: '(LOCAO HIDRAT AVEIA DAVENE T PELE 180ML|HIDRAT DAVENE LEITE|LEITE H.PAIXAO 200ML|HIDRAT DAVENE HIPOAL)', text: 'Hidratante de Pele'},
    {regex: '(INSET AERO UFA MULTI L400ML P300ML|INSET SBP 45 NOITES|INSET SBP AERO 380ML)', text: 'Inseticida'},
    {regex: '(IOG MORANGO DANONE 1350G|IOG DANONE ACTIVIA 1|BEBIDA LACTEA MORANGO PAULISTA 850G|LEITE FERM AMEIXA 0% ACTIVIA 1250G|IOG NESTLE 1250G MOR|IOG NESTLE 1250G VIT|BEB LACT PALISTA 850|BEB LACT PAULISTA 85)', text: 'Iogurte'},
    {regex: '(ASSOLAN 8UN 60G|LA ACO ASSOLAN 60g|LA ACO ASSOLAN 8UN|LA ACO ASSOLAN PROMO)', text: 'Lã de Aço'},
    {regex: '(LASANHA PETYBON 200G)', text: 'Lasanha'},
    {regex: '(LEITE DE COCO BOM COCO 200ML|LEITE COCO MENINA 20|LEITE COCO TRAD.200M)', text: 'Leite de Coco'},
    {regex: '(LEITE COND NILZA 395G|LEITE COND ITALAC TP 395G|LEITE CONDENS FRIMES|LEITE CONDENS JUSSAR)', text: 'Leite Condensado'},
    {regex: '(LEITE DESN CT ITALAC 1L|LEITE DESN.JUSSARA|LEITE DESNATADO NILZA 1LT|LEITE L VIDA BLINK 1|LEITE L VIDA MATILA|LEITE L VIDA TIROL 1|LEITE LONGA VIDA DESN ITALAC CT 1L|LEITE LONGA VIDA DESNAT PIRACANJUBA 1L|LEITE SHEFA)', text: 'Leite'},
    {regex: '(LEITE PO INT CCGL SCH 400G|LEITE PO INT ITALAC SCH 400G|LEITE PO ITALAC PC 4|LEITE PO ITAMBE SACH|LEITE PO PCT.200g|LEITE PO SACH ITAMBE)', text: 'Leite em Pó'},
    {regex: '(LIMP ZAP CLEAN M USO LARANJA 500ML|LIMP UAU LAVANDA 1L|LIMP UAU M USO 10 G|LIMP UAU MULTI USO LAVANDA 500ML|LIMP.M.USO.UAU LAV|LIMP.UAU LAVANDA|UAU LIMPEZA PERF 500)', text: 'Limpador UAU'},
    {regex: '(LIMP YPE M USO CLASSICO 500ML GTS 50ML|LUSTRA M.YPE JASMIM|LUSTRA MOVEIS YPE 20)', text: 'Lustra-Móveis'},
    {regex: '(LING CARNE SUINA CONG NOBRE 1KG|LING MARCHIORI FRANG|LING NOBRE SUINA MIS)', text: 'Linguiça Crua'},
    {regex: '(LING SEARA CALABRESA|CALABRESA SANTA ROSA|LING.CAL.PERDIGAO KG|LINGUICA CALABRESA SADIA KG|CALABRESA PERDIGAO D)', text: 'Linguiça Calabresa'},
    {regex: '(MAC OVOS LUCIANA ESPAGUETE 500G|MAC SEMOLA DAROZ ESPAGUETTI 2 500G|MAC SEMOLADO VITARELLA ESPAGUETE 500G)', text: 'Macarrão Espaguetti'},
    {regex: '(MAC SEMOLA GALO PARAFUSO 2 500G|MAC SEMOLADO BASILAR|MAC.SEM.GALO 500G|MAC.SEMOL.BASILAR|MACARRAO BASILAR SEM)', text: 'Macarrão Parafuso'},
    {regex: '(MAIONESE SUAVIT 500G|MAIONESE SUAVIT PT 500G)', text: 'Maionese'},
    {regex: '(MAIZENA 200G|AMIDO MILHO KININO 5|AMIDO MILHO QUERO 20)', text: 'Maisena'},
    {regex: '(FILE DE MERLUZA CONG JESSY SEAFOODS 800G|FILE DE MERLUZA CONG JESSY SEAFOODS 1KG|FILE MERLUZA KG|FILE PESCADA CONG COSTA SUL 500G|MERLUZA HG CONG.KG)', text: 'Merluza'},
    {regex: '(MILHO FUGINI 200G SA|MILHO FUGINI SACHET|MILHO VERDE STELA DORO 200G)', text: 'Milho'},
    {regex: '(MOLHO TOM TRAD REFOG PREDILECTA SCH 340G|MOLHO TOM TRAD PRIMOR SACHE 340G|MOLHO TRAD.PRED.340g|MOLHO VAL SACHE 340G)', text: 'Molho de Tomate'},
    {regex: '(OLEO SOJA SOYA PVC 9|OLEO COCAMAR PET 900|OLEO LEVE PET 900ML|OLEO SOJA CONCORDIA 900ML|OLEO SOJA SOYA 900ML|OLEO SOJA SUAVIT|OLEO SOJA V.VELHA)', text: 'Óleo de Soja'},
    {regex: '(OVOS ROFATTO GDE PVC C3)', text: 'Ovo (30)'},
    {regex: '(CHOCOTTONE BIG BOM K|PANETTONE CHOC POLLI CASA DORO 400G|PANETTONE FRUTAS POLLI CASA DORO 400G|PANETTONE FRUTAS NO PONTO KG|PANETTONE G.B.1KG)', text: 'Panetone'},
    {regex: '(PAO FORMA INTEGRAL PANCO 500G|PAO F.VISCONTI 400G|PAO F.WICK.INT.450G|PAO FORMA INTEGRAL VISCONTI 400G|PAO FORMA INTEGRAL WICKBOLD 550G|PAO NEWBREAD 500G 10|PAO NEWBREAD 500G IN|PAO NEWBREAD FORMA|PAO W BOLD 400G QUAD|PAO WICK BOLD 550G I)', text: 'Pão de Forma'},
    {regex: '(PAPEL HIG NEVE FD L12P11UN 30M|P HIG SUBLIME C 8UN|PAP.H.NEVE L12 P11|PAPEL HIG NEVE LV12|PAPEL HIG NEVE LV16|PAPEL HIG PERSONAL FS 4UN 30M)', text: 'Papel Higiênico'},
    {regex: '(POSTA SUINA C COURO KG)', text: 'Pernil Suíno'},
    {regex: '(PICANHA FATIADA KG)', text: 'Picanha'},
    {regex: '(PILHA RAYOVAC LV PG)', text: 'Pilha'},
    {regex: '(PRESUN FRIMESA PC|PRESUNTO FRIMESA S C)', text: 'Presunto'},
    {regex: '(QJO FUGINI 40G RALAD|QJO.RAL.VIGOR 50GR|QJO ITALAC 50G RALAD|QUEIJO PARMESAO RALADO ITALAC 50G|QUEIJO RALADO FIAPO TEIXEIRA 50G|QUEIJO RALADO TRAD TEIXEIRA 50G)', text: 'Queijo Ralado'},
    {regex: '(FC QJO MUSSARELA FAT|QJO MUSSARELA FAT|QUEIJO MUSSARELA FAT TRES MARIAS KG)', text: 'Queijo Muçarela'},
    {regex: '(REFRIG COCA COLA PET 2000ML TRAD + 250ML GTS|REFRIG FANTA PET 2000ML UVA)', text: 'Refrigerante'},
    {regex: '(REQUEIJAO TRAD VIGOR 200G|REQ SANTIAGO 220G|REQ.NESTLE LIGHT|REQ.VIGOR 200GR|REQUEIJAO TRAD SCALA 200G|REQUEIJAO TRAD TIROLEZ 200G|REQUEIJAO VIGOR COP)', text: 'Requeijão'},
    {regex: '(SAB LUX SUAVE ROSAS FRANCESAS 85G|SAB PROTEX LIMPEZA PROFUNDA 85G|SAB LUX SUAVE FLOR LOTUS 85G|SAB REXONA ANTIBACTERIAL ALOE 84G|SAB PROTEX MEN SPORT 85G|SAB FRANCIS SUAVE 85|SAB JOHNSON LAVANDA 80G|SAB JOHNSON LAVANDA E ALECRIM 90G|SAB JOHNSON OLEO AMEND 90G|SAB JOHNSONS 90GR|SAB NIVEA ANTIBACTER|SAB NIVEA HIDRATANTE|SAB PALMOLIVE SUAVE HID PERF ROSAS 85G|SAB PALMOLIVE SUAVE OLEO NUT CAMELIA 85G|SAB PROTEX COMPLETE 12 85G|SAB.ALBANY SVE.90GR|SAB.FRANCIS SVE.85G|SAB.PALM.85G|SABON.PALM.85G|SABON.PALM.ARGAN 85G|SABON.YPE BCO.90g|SABON.YPE ROSA 90g|SABON.YPE SVE.AMAR|SABONETE LIVY 90G|SABONETE NIVEA 85G)', text: 'Sabonete'},
    {regex: '(SABAO PED YPE 5X200G|SABAO PEDRA TRIEX 5U)', text: 'Sabão em Pedra'},
    {regex: '(LAVA ROUPA PO SURF F CEREJ LAVANDA 1KG|DET.PO TIXAN 1KG|DET.PO TIXAN 2KG|L ROUPA PO SURF 1 KG|L ROUPA PO SURF 1KG|LAVA ROUPA PO SURF HORTENCIA E F BCA 1KGALAVA ROUPA PO TIXAN PRIMAVERA 1KGALAVA ROUPA PO TIXAN PRIMAVERA 2KG)', text: 'Sabão em Pó'},
    {regex: '(SACO FREEZER WYDA 2K)', text: 'Saco Plástico'},
    {regex: '(SAPOLIO RADIUM 300G)', text: 'Sapólio'},
    {regex: '(SARDINHA OLEO ROBINSON CRUSOE 125G|SARD.COQUEIRO 125G|SARDINHA EVISC CONG COSTA SUL 800G)', text: 'Sardinha'},
    {regex: '(SAZON 60GR|TEMP.SAZON MAR.60G|TEMP.SAZON VERM.60G|TEMPARISCO PO 50g)', text: 'Sazon'},
    {regex: '(SH SEDA LISO PERFEITO 325ML|SH SUAVE 325ML|SH.SUAVE 325ML|SHAMPOO F VEGETAIS|SHAMPOO FARMAERVAS)', text: 'Shampoo'},
    {regex: '(SOJA SANJER GRAOS 50)', text: 'Soja'},
    {regex: '(SUCO MAGUARY LIMAO 1L|NECTAR MAGUARY LARANJA 1L|SUCO CAJU 1 LT|SUCO MARACUJA 1 LT|SUCO FR.CITRICAS 1 L|SUCO PESSEGO 1L)', text: 'Suco 1L'},
    {regex: '(REFRESCO DEL VALLE FRESH LARANJA 1.5L|REFRESCO DEL VALLE FRESH LIMAO 1.5L|BEB DEL VALLE FRESH)', text: 'Suco 1,5L'},
    {regex: '(SUCO GARIBALDI 1 5L|SUCO INTEGRAL UVA SALTON 1.5L|SUCO PANIZZON 1 5L|SUCO PANIZZON 1.5L|SUCO UVA 1.5 LTS)', text: 'Suco de Uva'},
    {regex: '(TEMP COMPLETO SABOR AMI 300G|TEMP.CPIM.AR.300g|TEMPERO HIKARI COMPL)', text: 'Tempero Completo'},
    {regex: '(TOALHA PAPEL SELECT 2UN|TOALHA PAPEL YURI 2|TOALHA YURI FIT C2)', text: 'Toalha Papel'},
    {regex: '(TRIGO KIBE SANJER 50)', text: 'Trigo para Quibe'},
    {regex: '(VASSOURA TOBIAS PRIM)', text: 'Vassoura'},
    {regex: '(VINAG.BELMONT ALCOOL|VINAG.BELMONT MACA|VINAGRE ALCOOL NEVAL 750ML|VINAGRE CASTELO 750M|VINAGRE FORTALEZA 75)', text: 'Vinagre'},
    {regex: '(VINHO C.GARCIA 750ML|VINHO CASAL GARCIA V)', text: 'Vinho'},
  ];
}

// *K* NECTAR MAGUARY CAJU 1L
// ABACAXI SCHRAMM CALD
// ACEM KG
// ACUCAR A ALEGRE 1KG
// ACUCAR BIG BOM 5KG C
// ACUCAR CARAVELAS 1KG
// ACUCAR MASCAVO LOWCU
// ACUCAR UNIAO DEMERAR
// ADOC ZERO CAL SACARI
// AGUA SANITARIA TRIEX
// ALBARUSKA 5KG PARBOI
// ALBARUSKA 5KG T 1
// ALCOOL GEL COPERALCO
// ALCOOL ZUMBI 1L
// ALHO GRANEL
// AMEIXA OLE LT 150G C
// AMENDOCREM 200G AMEN
// AMIDO MILHO KININO 5
// AMIDO MILHO QUERO 20
// APRESUN PEPERI FAT
// ARROZ PANELA FERRO 5
// ARROZ PILECCO 5KG PA
// ATUM BALTICO LT 170G
// ATUM ROBINSON CRUSOE
// AZEITE BALTICO CLASS
// AZEITONA DIZA 100
// BACON SADIA
// BEB LACT PALISTA 850
// BEB LACT PAULISTA 85
// BISC CHAMPAGNE MAGIT
// BISC TRIUNFO SALG 37
// BISC VIERA PRINCESA
// BISCOITO ZABET DOCE
// BOLO LEITE CONDENSAD
// BOMBOM GAROTO 250G S
// BOMBOM GAROTO 300G S
// BOMBOM LACTA 250 6G
// BOMBOM NESTLE 251G E
// BORR.M.USO 1001
// CABIDE SANREMO LV6 P
// CAFE 3 CORACOES 500G
// CAFE 3 CORACOES VACU
// CAFE COPPO 500G
// CALDO MAGGI 114G
// CANJICA HIKARI 500G
// CANJICA KININO 500G
// CANJICA SANJER BRANC
// CARGA GILLETE MACH3 REG 3UN
// CARNE ACEM MOIDO
// CEBOLA MEDIA
// CENOURA MEDIA
// CEPACOL 250ML
// CEREAL ALCAFOODS FLA
// CERESER MACA 660ML S
// CERV PETRA LT 350ML
// CERV.BHAM.MALZ.355ML
// CERV.ITAI.MALZ.350ML
// CHA D OETKER 15G CAM
// CHANTILLY FLEISCHMAN
// CHOC GAROTO BARRA 90
// CHOCO B BOM 500G
// CHOCOLATE PO HIKARI
// CHOCOTTONE BIG BOM K
// CHOPP A OUTRA LT 269
// CJ CR DENT COLGATE T
// CJ TRESEMME SH 400ML
// COCO RALADO MENINA 5
// COCO RALADO SOCOCO 1
// COND F VEGETAIS BL
// COND F VEGETAIS PLAT
// COND SUAVE 325ML
// COND TRESEMME 400ML
// COND.TRIANGULO TP
// CONDICIONADOR KOLEN
// COPO NADIR GINGA CRI
// COPO NADIR LIGHT L
// COXA C SOBRECOXA KG
// CR CHANTMIX AMELIA 2
// CR DENT COLGATE NATU
// CR DENT ORAL B 123 7
// CR DENT ORAL B ANTI
// CR DENTAL COLGATE NA
// CR DENTAL COLGATE TO
// CR LEIT/E SHEFA TP 20
// CR LEITE PIRACANJUBA
// CR PENTEAR PANTENE 2
// CR VEGETAL BECEL 500
// CR YAMASTEROL 200G A
// DES AERO SUAVE MEN 1
// DES AERO SUAVE WOMAN
// DES STICK GILLETTE C
// DES.CR.REXONA 48G
// DESINF LYSOFORM 1L S
// DESINF TRIEX 2L
// DESINFETANTE URCA EU
// DESOD SPRAY SENADOR CLASSIC 90ML
// DOCE ABOBORA BATATA BOIZINHO 260G
// DOCE MOCOTO BOIZINHO 140G
// DOCE TRIANGULO 400g
// DOCES SALMAO 450G SORTIDO
// ERVA DOCE SANJER 20G
// ERVILHA QUERO SACHE
// ESC DENT J J TEK DU
// ESC DENT SORRISO TRI
// ESFOLIANTE NEUTROG 1
// ESP CANELA CASCA 20G
// ESP SANJ 20G P GRAO
// ESPONJA BRILHUS M US
// ESPONJA ESFRELUX C 4
// ESPUMA GILLETTE 175G
// ESPUMA PRESTOBARBA B
// EXTRATO ELEFANTE LT
// EXTRATO ELEFANTE PET
// FACA YANGZI INOX VER
// FARINHA TRIGO RENATA
// FC APRESUNTADO PEPER
// FC QJO MUSSARELA FAT
// FEIJAO CABRERA 2KG
// FEIJAO CABRERA PRETO
// FEIJAO CAIPIRA 2KG C
// FEIJAO KIBELLO 1KG C
// FEIJAO SOBRADINHO 1K
// FERMENTO BIOL D OET
// FERMENTO PO D OETKER
// FERMENTO PO ROYAL 10
// FERMENTO QUIMICO APT
// FIGO SCHRAMM 440G
// FILTRO PACAEMBU 103
// FIO DENTAL COLGATE 5
// FITA DENTAL COLGATE
// FRALDA DESC PAMPERS
// FRUTA CRISTALIZADA
// FT LARANJA PERA EXTR
// FT MARACUJA AZEDO
// FT MORANGO 250G
// FUBA SANJER 500G MIM
// FUBA SANJER MIMOSO 5
// GARFO MESA YANGZI LA
// GARRAFA PLASDURAM 1L
// GLACUCAR UNIAO 500G
// GUARD LIPS FS 50UN 23.5X24CM 3107 G9
// HIDRATANTE DAVENE AV
// HIKARI 30G CANELA PO
// HIKARI 30G ERVA DOCE
// HIKARI 70G BICARBON
// HIKARI 7G MANJERIC
// INSET RAID AERO 420M
// IOG DANONE 1350G VIT
// IOG DANONE ACTIVIA Z
// IOG PAULISTA LIQ 850
// JARRAS POTE IGARATIB
// JG COPO NADIR C 6 GI
// L ROUPA APYCE 1KG
// L ROUPA PO SURF 800G
// LAMPADA KIAN LED 9W
// LARANJA PERA A GRANEL KG
// LASANHA OVOS DE 500G
// LAVA LOUCA MINUANO 5
// LEITE CONDENS PIRACA
// LEITE CONDENS TIROL
// LEITE JUSSARA 1L TP
// LEITE JUSSARA MAX PE
// LEITE PIRACANJUBA 1L
// LEITE PO PIRACANJUBA
// LIMP UAU M USO 500ML
// LIMP UAU MULTIUSO 50
// LIMP UAU PERFUMES LV
// LIMPADOR UAU MULTI U
// LIMPADOR VIM CLORO A
// LING TOSCANA BIGBOM
// LUSTRA MOV BRAVO CLA
// LUSTRA MOVEIS BRAVO
// MAC BARILLA 500G ESP
// MAC GALO SEMOLADO 50
// MAC S AMALIA OVOS 50
// MAC STA AMALIA SEMOL
// MACARRAO GALO SEMOLA
// MAIONESE HELLMANNS 5
// MANTEIGA AVIACAO TA
// MARGARINA BECEL 500G
// MASSA PASTEL GUACU 1
// MASSA PASTEL HIRATA
// MASSA PASTEL SIORELLA 500G
// MILHO PIPOCA SANJER
// MIST BOLO APTI 400G
// MIST BOLO ITALAC LARANJA 400G
// MOLHO FUGINI SACHE 3
// MOLHO PIMENTA CEPERA
// NEDO ABRIDOR FURADOR
// NOZES S CASCA
// OLEO COAMO PET 900ML
// OLEO CONCORDIA PET 9
// OLEO SOYA PET 900ML
// ORAL B 25M SAT FLOSS
// OVO SATOSHI 30UN GDE
// PALITO DENTE PARANA
// PALITO GINA 200UN 102
// PAO BAUDUCCO 400G IN
// PAO PANCO 500G FORMA
// PAO SOVADO KG
// PAO VISCONTI INTEGRA
// PAO WICK BOLD 450G I
// PAO WICK BOLD 500G I
// PAPEL HIGIENICO NEV
// PEIXE DESF TP BAC DES RIBERALVES 500G
// PERA WILIANS
// PERNIL COSSO KG
// PERNIL S OSSO
// PESSEGO SCHRAMM 450G
// PESSEGO SCHRAMM CALD
// PIPOCA HIKARI TRAD 5
// PIPOCA KISABOR 500G
// PO GELATINA APTI 35G
// PO MARIA MOLE APTI 5
// PO MARIA MOLE OETKER
// POTE PREMIUM PLASTUT
// PRESTOBARBA ULTRA GR
// PROTETOR LABIAL NIVE
// QJO DINAPOLI 50G
// QJO MUSSARELA FT KG
// QJO RALADO BIG 50G
// RALADOR YANGZI FOUR
// REFIL GILLETTE MACH3
// REFRESCO PO MID 25G
// REPEL RAID 30N REFIL
// REPEL RAID ELETR LIQ
// REPEL RAID LIQ C 2 5
// REPOLHO VERDE
// REQ SANTIAGO 200G
// REQUEIJAO FRIMESA 18
// RODO STA MARIA PLAST
// S AMALIA SEMOLA 500G
// SAB FLOR YPE SUAVE 9
// SAB J J 90G
// SAB JOHNSONS 80G
// SAB LIQ F VEGETAIS 3
// SAB LIQ TOK BOTHANIC
// SAB LUX SUAVE 85G
// SAB MOTIVUS 90G
// SAB PALMOLIVE NATURA
// SAB PHEBO 90G
// SAB REXONA 84G
// SABAO MINUANO GLICER
// SABAO RAZZO 200G TIR
// SABAO YPE PEDRA 5UN
// SABONETE PALMOLIVE 1
// SAL CISNE REFINADO 1
// SAL REF.LEBRE 1
// SAL REFINADO SELECT 1KG
// SAL UNIAO 1KG REFINA
// SANJER 40G BIC SODIO
// SANJER 8G OREGANO
// SAPONACEO SAPOLIO RA
// SARDINHA ROBINSON CR
// SELECTA 100G LIGA NE
// SHAMPOO TRESEMME 400
// SOPA KNORR 38G
// STEAK PEIXE COSTA SUL 120G
// SUCO PANIZZON 1 5L U
// SUCO STA LARANJA 2L
// SUCO UVA AURORA 1 5L
// SUCO UVA GARIBALDI 1
// SUCO VITA SUCO 1 5L
// SUCO VITA SUCO TP 1L
// TACA NADIR 260ML VIN
// TACA NADIR GALLANT V
// TALHER TRAMONT ACO I
// TANGERINA PONKAN kg
// TEMP SABOR AMI 300G
// TEMPERO ARISCO 300G
// TEMPERO SAZON 60GR
// TENDER PAMPLONA KG
// TIRA MANCHA YPE 500M
// TOALHA PAPEL NATUREZ
// TOALHA PAPEL YURI FI
// TRIGO KIBE HIKARI 50
// TRIGO NONITA 1KG
// UNIAO 1KG REFINADO C
// UVA PASSA PTA S SEM
// VASSOURA TOBIAS MAX
// VINHO FRISANTE DONNA
// VINHO L DONNA LAMBRU
